apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: {{ quote .Values.name }}
    visualize: "true"
  name: {{ quote .Values.name }}
spec:
  ports:
  - port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.port }}
    name: http    
  selector:
    run: {{ quote .Values.name }}
    serving: "true"    
  type: NodePort
status:
  loadBalancer: {}