apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: order-fault
spec:
  hosts:
  - order.default.svc.cluster.local
  http:
  - fault:
      abort:
        percent: 100
        httpStatus: 500
    route:
    - destination:
        host: order.default.svc.cluster.local