apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: bonus
    app: bonus
    version: "1.0"
    visualize: "true"        
  name: bonus
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bonus
      app: bonus
      version: "1.0"
      serving: "true"    
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: bonus
        app: bonus
        version: "1.0"
        serving: "true"    
        visualize: "true"                
    spec:
      containers:
      - name: bonus
        image: microservice-istio-bonus:1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: bonus
    visualize: "true"
  name: bonus
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http    
  selector:
    run: bonus
    serving: "true"    
  type: NodePort
status:
  loadBalancer: {}

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bonus
spec:
  hosts:
  - "*"
  gateways:
  - microservice-gateway
  http:
  - match:
    - uri:
        prefix: /bonus
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 8080
        host: bonus.default.svc.cluster.local
